import os
import re
from fpdf import FPDF
from datetime import datetime
from mos_bot.config import PDFS_DIR


class ProgramPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 6)
            self.set_text_color(160, 160, 160)
            self.cell(95, 4, "Muscle OS -- Coaching Program", align="L")
            self.cell(95, 4, f"Page {self.page_no()}/{{nb}}", align="R",
                      new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(220, 220, 220)
            self.line(10, 10, 200, 10)
            self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 6)
        self.set_text_color(180, 180, 180)
        self.cell(0, 8, "Generated by Muscle OS -- AI Coaching System", align="C")

    def section_title(self, num, title):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(12, 34, 56)
        title = self._sanitize(title)
        self.cell(0, 8, f"{num}. {title}", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(12, 34, 56)
        self.set_line_width(0.5)
        self.line(10, self.get_y() + 1, 200, self.get_y() + 1)
        self.ln(5)

    def sub_heading(self, text):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(30, 30, 30)
        text = self._sanitize(text)
        self.cell(0, 6, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body_text(self, text, size=8.5):
        text = self._sanitize(text)
        self.set_font("Helvetica", "", size)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 4.5, text, align="L", new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def bullet(self, text, indent=5, size=8.5):
        text = self._sanitize(text)
        self.set_font("Helvetica", "", size)
        self.set_text_color(60, 60, 60)
        x = self.get_x() + indent
        self.set_x(x)
        self.cell(4, 4.5, "-", new_x="END")
        self.multi_cell(190 - indent - 6 - 4, 4.5, text, new_x="LMARGIN", new_y="NEXT")

    def table_row(self, cells, widths, header=False):
        cells = [self._sanitize(c) for c in cells]
        h = 5.5
        y = self.get_y()
        if y + h > 270:
            self.add_page()
            y = self.get_y()
        if header:
            self.set_font("Helvetica", "B", 7)
            self.set_fill_color(240, 242, 245)
            self.set_text_color(80, 80, 80)
        else:
            self.set_font("Helvetica", "", 7)
            self.set_text_color(50, 50, 50)
        x = 10
        self.set_draw_color(220, 220, 220)
        for i, (cell, w) in enumerate(zip(cells, widths)):
            self.set_xy(x, y)
            self.cell(w, h, cell, border=1, align="L", fill=header)
            x += w
        self.set_xy(10, y + h)
        return y + h

    def _sanitize(self, text: str) -> str:
        replacements = {
            '\u2014': '--', '\u2013': '-',
            '\u2018': "'", '\u2019': "'",
            '\u201c': '"', '\u201d': '"',
            '\u2022': '*', '\u2026': '...',
            '\u2192': '->', '\u2190': '<-',
            '\u2713': 'v', '\u2717': 'x',
            '\u2020': '+', '\u2021': '++',
            '\u2122': '(TM)', '\u00ae': '(R)', '\u00a9': '(C)',
            '\u20ac': 'EUR', '\u00a0': ' ',
            '\ufb01': 'fi', '\ufb02': 'fl',
        }
        for old, new in replacements.items():
            text = text.replace(old, new)
        try:
            text.encode('latin-1')
        except UnicodeEncodeError:
            text = text.encode('latin-1', errors='replace').decode('latin-1')
        return text


def markdown_to_pdf(markdown: str, output_path: str) -> str:
    pdf = ProgramPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    lines = markdown.split("\n")
    section_counter = 0
    table_buffer = []
    in_table = False
    in_code = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue

        if "|" in stripped and stripped.count("|") > 2:
            table_buffer.append(line)
            in_table = True
            continue
        else:
            if in_table and table_buffer:
                _render_table(pdf, table_buffer)
                table_buffer = []
                in_table = False

        if not stripped:
            continue

        if stripped.startswith("# ") or stripped.startswith("## ") or stripped.startswith("### "):
            level = stripped.count("#")
            title = stripped.lstrip("#").strip()
            title = re.sub(r"\*\*(.*?)\*\*", r"\1", title)
            if level <= 1:
                section_counter += 1
                pdf.add_page()
                pdf.section_title(section_counter, title)
            elif level == 2:
                pdf.sub_heading(title)
            else:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(60, 60, 60)
                pdf.cell(0, 5, pdf._sanitize(title), new_x="LMARGIN", new_y="NEXT")
                pdf.ln(1)
        elif stripped.startswith("- ") or stripped.startswith("* "):
            text = stripped[2:]
            text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
            pdf.bullet(text)
        elif stripped.startswith("**") and stripped.endswith("**"):
            text = stripped.strip("*")
            pdf.sub_heading(text)
        elif stripped.startswith("|"):
            pass
        else:
            text = re.sub(r"\*\*(.*?)\*\*", r"\1", stripped)
            pdf.body_text(text)

    if in_table and table_buffer:
        _render_table(pdf, table_buffer)

    pdf.output(output_path)
    return output_path


def _render_table(pdf, lines):
    rows = []
    for line in lines:
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if all(set(c) <= set("-: ") for c in cells):
            continue
        rows.append(cells)
    if not rows:
        return
    col_count = len(rows[0])
    widths = [min(190 // col_count, 40) for _ in range(col_count)]
    gap = 190 - sum(widths)
    if gap > 0:
        widths[-1] += gap
    pdf.table_row(rows[0], widths, header=True)
    for row in rows[1:]:
        while len(row) < col_count:
            row.append("")
        pdf.table_row(row[:col_count], widths)


def generate_program_pdf(markdown: str, user_id: str) -> str:
    os.makedirs(PDFS_DIR, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(PDFS_DIR, f"{user_id}_program_{ts}.pdf")
    try:
        return markdown_to_pdf(markdown, path)
    except Exception:
        return None
